"""create

Revision ID: 4d1521c68268
Revises: 6cb8ed9715a5
Create Date: 2025-05-27 11:37:26.061387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d1521c68268'
down_revision = '6cb8ed9715a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.add_column('locations', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_manufacturers_id'), table_name='manufacturers')
    op.create_unique_constraint('_product_location_uc', 'product_stock', ['product_id', 'location_id'])
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('variation', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_unique_constraint(None, 'products', ['sku'])
    op.drop_column('products', 'name')
    op.drop_column('products', 'description')
    op.drop_column('products', 'price')
    op.create_unique_constraint('_user_product_location_uc_cart', 'user_cart', ['user_id', 'product_id', 'location_id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('_user_product_location_uc_cart', 'user_cart', type_='unique')
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'cost')
    op.drop_column('products', 'variation')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'sku')
    op.drop_constraint('_product_location_uc', 'product_stock', type_='unique')
    op.create_index(op.f('ix_manufacturers_id'), 'manufacturers', ['id'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.drop_column('locations', 'address')
    op.add_column('categories', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'])
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.create_table('stock',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('stock_location_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('stock_product_id_fkey')),
    sa.PrimaryKeyConstraint('product_id', 'location_id', name=op.f('stock_pkey'))
    )
    # ### end Alembic commands ###






